name: Run tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Test parser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v1
      - name: Run parser and binding tests
        uses: tree-sitter/parser-test-action@v2
        with:
          generate: false
    
  test-against-c3c:
    name: Test against stdlib and test suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: source
      - name: Checkout c3lang/vendor
        uses: actions/checkout@v4
        with:
          repository: c3lang/vendor
          path: vendor
      - name: Download latest release
        uses: robinraju/release-downloader@v1.12
        with:
          repository: c3lang/c3c
          latest: true
          fileName: c3-ubuntu-22.tar.gz
          tarBall: true
          zipBall: false
          extract: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install tree-sitter
        uses: tree-sitter/setup-action@v1
        with:
          install-lib: true
          install-cli: false
      - name: DEBUG
        run: |-
          echo $LD_LIBRARY_PATH
      - name: Run tests
        run: |-
          pushd source/test_runner
          ../../c3/c3c run --libdir ../../vendor/libraries --libdir ../bindings/c3 -L $LD_LIBRARY_PATH -- ../../c3/c3c ../../c3/lib $(find $GITHUB_WORKSPACE -type d -name 'test_suite')
          popd
          
    
